
FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS base
USER $APP_UID
WORKDIR /app
EXPOSE 8080

# Build stage
FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
ARG BUILD_CONFIGURATION=Release
WORKDIR /src

# Copia apenas o csproj para cache
COPY ["src/PaymentsProcessorService.Api/PaymentsProcessorService.Api.csproj", "src/PaymentsProcessorService.Api/"]
RUN dotnet restore "src/PaymentsProcessorService.Api/PaymentsProcessorService.Api.csproj"





# Copia TODO o código agora
COPY . .
WORKDIR /src/src/PaymentsProcessorService.Api

RUN dotnet build "PaymentsProcessorService.Api.csproj" -c $BUILD_CONFIGURATION -o /app/build

#publish stage
FROM build AS publish
ARG BUILD_CONFIGURATION=Release
RUN dotnet publish "PaymentsProcessorService.Api.csproj" -c $BUILD_CONFIGURATION -o /app/publish /p:UseAppHost=false

# Final stage
FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "src/PaymentsProcessorService.Api.dll"]